name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: cd
      run: cd linuxdoom-1.10
    - name: make
      run: sudo make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
